import { Task } from "@/lib/types/task";

export const tasks: Task[] = [
  {
    jobId: "task-1",
    jobType: "fixed",
    title: "Website Redesign for Small Business",
    description: "Looking for an experienced web designer to redesign our company website. Need modern, responsive design with e-commerce integration.",
    category: "Tech Services",
    subCategory: "Web Development",
    itemType: "Website Design",
    fixedPrice: 2500,
    price: 2500,
    lat: 40.7128,
    lng: -74.006,
    address: "123 Main St, New York, NY 10001",
    completionStatus: "open",
    proposalAcceptance: "open",
    clientId: "user-5",
    urgency: "normal",
    isVerified: true,
    posterType: "company",
    posterName: "ABC Company",
    photos: ["https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800"],
    skills: ["Web Design", "React", "E-commerce"],
    tags: ["urgent", "design"],
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
  },
  {
    jobId: "task-2",
    jobType: "hourly",
    title: "House Cleaning - 3 Bedroom Apartment",
    description: "Need deep cleaning for 3 bedroom apartment. Moving out cleaning required. Must be completed by end of week.",
    category: "Home Services",
    subCategory: "Cleaning",
    itemType: "Deep Cleaning",
    hourlyRate: 45,
    estimatedDuration: 4,
    price: 180,
    lat: 34.0522,
    lng: -118.2437,
    address: "456 Oak Ave, Los Angeles, CA 90001",
    completionStatus: "open",
    proposalAcceptance: "open",
    clientId: "user-5",
    urgency: "high",
    isVerified: false,
    posterType: "individual",
    posterName: "David Brown",
    skills: ["House Cleaning", "Deep Cleaning"],
    tags: ["urgent"],
    createdAt: "2024-01-21T08:00:00Z",
    updatedAt: "2024-01-21T08:00:00Z",
  },
  {
    jobId: "task-3",
    jobType: "fixed",
    title: "Fix Leaky Kitchen Faucet",
    description: "Kitchen faucet is leaking. Need immediate repair. Must have proper tools and experience.",
    category: "Home Services",
    subCategory: "Plumbing",
    itemType: "Leak Repair",
    fixedPrice: 150,
    price: 150,
    lat: 41.8781,
    lng: -87.6298,
    address: "789 Elm St, Chicago, IL 60601",
    completionStatus: "open",
    proposalAcceptance: "open",
    clientId: "user-5",
    urgency: "urgent",
    isVerified: false,
    posterType: "individual",
    skills: ["Plumbing", "Repair"],
    tags: ["urgent", "emergency"],
    createdAt: "2024-01-22T14:00:00Z",
    updatedAt: "2024-01-22T14:00:00Z",
  },
  {
    jobId: "task-4",
    jobType: "fixed",
    title: "Logo Design and Brand Identity",
    description: "Startup company needs professional logo design and complete brand identity package. Looking for creative designer.",
    category: "Tech Services",
    subCategory: "Web Development",
    itemType: "Branding",
    fixedPrice: 800,
    price: 800,
    lat: 29.7604,
    lng: -95.3698,
    address: "321 Pine St, Houston, TX 77001",
    completionStatus: "open",
    proposalAcceptance: "open",
    clientId: "user-5",
    urgency: "normal",
    isVerified: true,
    posterType: "company",
    posterName: "Tech Startup Inc",
    skills: ["Graphic Design", "Logo Design", "Branding"],
    tags: ["design"],
    createdAt: "2024-01-19T12:00:00Z",
    updatedAt: "2024-01-19T12:00:00Z",
  },
  {
    jobId: "task-5",
    jobType: "hourly",
    title: "Personal Training Sessions",
    description: "Looking for certified personal trainer for weekly sessions. Focus on strength training and weight loss.",
    category: "Personal Care",
    subCategory: "Fitness",
    itemType: "Personal Training",
    hourlyRate: 70,
    estimatedDuration: 8,
    price: 560,
    lat: 39.9526,
    lng: -75.1652,
    address: "654 Maple Dr, Philadelphia, PA 19101",
    completionStatus: "open",
    proposalAcceptance: "open",
    clientId: "user-5",
    urgency: "normal",
    isVerified: false,
    posterType: "individual",
    skills: ["Personal Training", "Fitness", "Weight Loss"],
    tags: ["fitness"],
    createdAt: "2024-01-18T16:00:00Z",
    updatedAt: "2024-01-18T16:00:00Z",
  },
  {
    jobId: "task-6",
    jobType: "fixed",
    title: "Office Deep Cleaning",
    description: "Large office space (2000 sq ft) needs deep cleaning. Includes carpets, windows, and restrooms.",
    category: "Home Services",
    subCategory: "Cleaning",
    itemType: "Office Cleaning",
    fixedPrice: 500,
    price: 500,
    lat: 33.4484,
    lng: -112.074,
    address: "987 Business Blvd, Phoenix, AZ 85001",
    completionStatus: "open",
    proposalAcceptance: "open",
    clientId: "user-5",
    urgency: "normal",
    isVerified: true,
    posterType: "company",
    posterName: "Corporate Office",
    skills: ["Office Cleaning", "Deep Cleaning"],
    tags: ["commercial"],
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-17T09:00:00Z",
  },
];

export function getTaskById(id: string): Task | undefined {
  return tasks.find((task) => task.jobId === id);
}

export function getTaskBySlug(slug: string): Task | undefined {
  return tasks.find((task) => task.jobId === slug);
}

export function getTasksByCategory(category: string): Task[] {
  return tasks.filter((task) => task.category === category || task.subCategory === category);
}

export function getOpenTasks(): Task[] {
  return tasks.filter((task) => task.completionStatus === "open");
}

export function getTasksByClientId(clientId: string): Task[] {
  return tasks.filter((task) => task.clientId === clientId);
}

