import { User, UserProfile } from "@/lib/types/user";

export const users: User[] = [
  {
    id: "user-1",
    email: "john.doe@example.com",
    username: "johndoe",
    fullName: "John Doe",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
    uid: "user-1",
    phoneNumber: "+1234567890",
    role: "provider",
    currentRole: "provider",
    location: "New York, NY",
    latitude: 40.7128,
    longitude: -74.006,
    description: "Experienced web developer with 10+ years in the industry. Specialized in React and Node.js.",
    photos: [],
    isVerified: true,
    totalRating: 4.8,
    totalReviews: 127,
    rate: 75,
    completedAt: 89,
    skills: ["React", "Node.js", "TypeScript", "Next.js", "MongoDB"],
    createdAt: "2023-01-15T10:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "user-2",
    email: "jane.smith@example.com",
    username: "janesmith",
    fullName: "Jane Smith",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    uid: "user-2",
    phoneNumber: "+1234567891",
    role: "provider",
    currentRole: "provider",
    location: "Los Angeles, CA",
    latitude: 34.0522,
    longitude: -118.2437,
    description: "Professional graphic designer and UI/UX expert. Creating beautiful digital experiences.",
    photos: [],
    isVerified: true,
    totalRating: 4.9,
    totalReviews: 203,
    rate: 85,
    completedAt: 156,
    skills: ["Graphic Design", "UI/UX", "Figma", "Adobe Creative Suite", "Branding"],
    createdAt: "2022-06-10T10:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z",
  },
  {
    id: "user-3",
    email: "mike.johnson@example.com",
    username: "mikej",
    fullName: "Mike Johnson",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    uid: "user-3",
    phoneNumber: "+1234567892",
    role: "provider",
    currentRole: "provider",
    location: "Chicago, IL",
    latitude: 41.8781,
    longitude: -87.6298,
    description: "Licensed plumber with 15 years of experience. Available for emergency repairs and installations.",
    photos: [],
    isVerified: true,
    totalRating: 4.7,
    totalReviews: 94,
    rate: 60,
    completedAt: 201,
    skills: ["Plumbing", "Pipe Repair", "Installation", "Water Heater", "Drain Cleaning"],
    createdAt: "2021-03-20T10:00:00Z",
    updatedAt: "2024-01-19T10:00:00Z",
  },
  {
    id: "user-4",
    email: "sarah.williams@example.com",
    username: "sarahw",
    fullName: "Sarah Williams",
    photoUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
    uid: "user-4",
    phoneNumber: "+1234567893",
    role: "provider",
    currentRole: "provider",
    location: "Houston, TX",
    latitude: 29.7604,
    longitude: -95.3698,
    description: "Professional house cleaner with attention to detail. Eco-friendly products available.",
    photos: [],
    isVerified: true,
    totalRating: 4.9,
    totalReviews: 178,
    rate: 45,
    completedAt: 312,
    skills: ["House Cleaning", "Deep Cleaning", "Office Cleaning", "Move-in/Move-out"],
    createdAt: "2022-08-05T10:00:00Z",
    updatedAt: "2024-01-21T10:00:00Z",
  },
  {
    id: "user-5",
    email: "david.brown@example.com",
    username: "davidb",
    fullName: "David Brown",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
    uid: "user-5",
    phoneNumber: "+1234567894",
    role: "client",
    currentRole: "client",
    location: "Phoenix, AZ",
    latitude: 33.4484,
    longitude: -112.074,
    description: "Small business owner looking for reliable service providers.",
    photos: [],
    isVerified: false,
    totalRating: 0,
    totalReviews: 0,
    completedAt: 0,
    skills: [],
    createdAt: "2023-11-12T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "user-6",
    email: "emily.davis@example.com",
    username: "emilyd",
    fullName: "Emily Davis",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop",
    uid: "user-6",
    phoneNumber: "+1234567895",
    role: "provider",
    currentRole: "provider",
    location: "Philadelphia, PA",
    latitude: 39.9526,
    longitude: -75.1652,
    description: "Certified personal trainer and nutrition coach. Helping you achieve your fitness goals.",
    photos: [],
    isVerified: true,
    totalRating: 4.8,
    totalReviews: 145,
    rate: 70,
    completedAt: 98,
    skills: ["Personal Training", "Yoga", "Nutrition", "Weight Loss", "Strength Training"],
    createdAt: "2022-09-15T10:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
  },
];

export function getUserById(id: string): User | undefined {
  return users.find((user) => user.id === id);
}

export function getUserBySlug(slug: string): User | undefined {
  return users.find((user) => user.id === slug || user.username === slug);
}

export function getProviders(): User[] {
  return users.filter((user) => user.currentRole === "provider" || user.role === "provider");
}

export function getClients(): User[] {
  return users.filter((user) => user.currentRole === "client" || user.role === "client");
}

