"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "english" | "french";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  english: {
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.close": "Close",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.clear": "Clear",
    "common.apply": "Apply",
    "common.or": "Or",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.explore": "Explore",
    "nav.reels": "Reels",
    "nav.showcasework": "Showcase Work",
    "nav.showcase": "Showcase",
    "nav.mytasks": "My Tasks",
    "nav.messages": "Messages",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.chatzing": "Chat Zing",
    "plus.chatzingAi": "ChatZing AI",
    "nav.home": "Home",
    "nav.postajob": "Post a Job",
    "nav.alljobs": "All Jobs",
    "nav.darkMode": "Dark Mode",
    
    // Settings
    "settings.title": "Settings",
    "settings.description": "Manage your settings and preferences",
    "settings.darkLightMode": "Dark/Light Mode",
    "settings.currentlyLight": "Currently: Light Mode",
    "settings.currentlyDark": "Currently: Dark Mode (Blue Theme)",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.system": "System",
    "settings.paymentMethod": "Payment Method",
    "settings.addAccountDetails": "Add your account details",
    "settings.addPayment": "Add Payment",
    "settings.notifications": "Notifications",
    "settings.toggleNotifications": "Toggle to turn off the notifications",
    "settings.suggestions": "Suggestions & Complaints",
    "settings.suggestionsDesc": "Share your feedback or report issues to help us improve",
    "settings.submitFeedback": "Submit Feedback",
    "settings.terms": "All Terms & Conditions",
    "settings.termsDesc": "View all terms by category (General, Provider, User, Post Job, Showcase Work, Legal)",
    "settings.viewTerms": "View Terms",
    "settings.language": "Language",
    "settings.chooseLanguage": "Choose your preferred language",
    "settings.english": "English",
    "settings.french": "French",
    "settings.accountDeactivation": "Account Deactivation",
    "settings.deactivateAccount": "Deactivate your account",
    "settings.deactivate": "Deactivate",
    "settings.logOut": "Log Out",
    "settings.signOut": "Sign out of your account",
    "settings.loggingOut": "Logging out...",
    "settings.changePasswordTitle": "Change password",
    "settings.changePasswordDesc": "Update your TaskZing account password",
    "settings.changePassword.back": "Back",
    "settings.changePassword.current": "Current password",
    "settings.changePassword.new": "New password",
    "settings.changePassword.confirm": "Confirm new password",
    "settings.changePassword.save": "Save",
    "settings.changePassword.saving": "Saving…",
    "settings.changePassword.mismatch": "Passwords do not match",
    "settings.changePassword.success": "Password updated. Other devices were signed out.",
    "settings.changePassword.failed": "Could not update password. Please try again.",
    "settings.changePassword.forgotLink": "Forgot your current password? Send reset email",
    "settings.twoFactor": "Two-factor authentication",
    "settings.twoFactorDesc": "Authenticator app (TOTP)",
    "settings.reels": "Reels",
    "settings.reelsDesc": "Watch and upload short videos",
    "settings.notificationsOn": "Notifications turned on",
    "settings.notificationsOff": "Notifications turned off",
    "settings.confirmLogoutTitle": "Log Out",
    "settings.confirmLogoutMessage": "Sign out of your account?",
    "settings.cancel": "Cancel",
    "settings.accountDeletion": "Account Deletion",
    "settings.accountDeletionDesc": "Permanently delete your account after a 90-day period",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteAccountDesc": "Permanently delete your account",
    "settings.deactivationConfirmTitle": "Confirm deactivation",
    "settings.deactivationConfirmMessage":
      "Your account will be deactivated. You can contact support to reactivate. Continue?",
    "settings.deactivationSuccess": "Account deactivated. You have been signed out.",
    "settings.deactivationFailed": "Deactivation failed",
    "settings.deactivating": "Deactivating account…",
    "settings.deletionConfirmTitle": "Confirm permanent deletion",
    "settings.deletionConfirmMessage":
      "Your account will be deactivated now and permanently deleted after 90 days. You can reactivate within 90 days to cancel. After 90 days, your data will be automatically deleted. This cannot be undone. Continue?",
    "settings.deletionConfirmButton": "Yes, delete my account",
    "settings.deletionSuccess":
      "Deletion requested. Your account will be permanently deleted within 90 days.",
    "settings.deletionFailed": "Request failed",
    "settings.deletionInfo":
      "Your account will be deactivated and scheduled for permanent deletion after 90 days. You can reactivate within 90 days to cancel. After 90 days, your data is automatically and permanently deleted.",
    "settings.deletionReasonTitle": "Select a reason for permanently deleting your account",
    "settings.requestPermanentDeletion": "Request permanent deletion",
    "settings.deletionEmailHint": "Or request by email:",
    "settings.deletionEmailBody":
      "I would like to request permanent deletion of my TaskZing account.",
    "settings.deletionEmailSubject": "Account Deletion Request",
    "settings.deletionEmailOpened":
      "Your email client will open. Please send the email to complete your request.",
    "settings.deletionEmailFailed": "Could not open email client. Please email us directly at",
    "settings.feedbackSuccess":
      "Thank you for your feedback! Your submission has been received.",

    "twoFa.title": "Two-factor authentication",
    "twoFa.back": "Back",
    "twoFa.disabledDescription":
      "Protect your account with two-factor authentication. You will scan a QR code, confirm with a code sent to your email, then receive one-time backup codes.",
    "twoFa.enabledDescription":
      "Two-factor authentication is on. To sign in, you will also use a code sent to your email.",
    "twoFa.startSetup": "Start setup",
    "twoFa.sendEnableCode": "Send enable code to email",
    "twoFa.enterEmailCode": "Enter the code from your email",
    "twoFa.enableButton": "Enable 2FA",
    "twoFa.secretLabel": "Secret",
    "twoFa.turnOffTitle": "Turn off 2FA",
    "twoFa.password": "Password",
    "twoFa.backupCodeOptional": "Backup code (optional if using email code)",
    "twoFa.sendDisableCode": "Send disable code to email",
    "twoFa.emailCode": "Email code",
    "twoFa.disableButton": "Disable 2FA",
    "twoFa.saveBackupCodes": "Save backup codes",
    "twoFa.enableCodeSent": "Enable code sent to your email",
    "twoFa.disableCodeSent": "Disable code sent to your email",
    "twoFa.enabledSuccess": "Two-factor authentication enabled",
    "twoFa.disabledSuccess": "Two-factor authentication disabled",
    "twoFa.passwordRequired": "Password is required",
    "twoFa.codeSixDigits": "Enter the 6-digit code from your email",
    "twoFa.errorGeneric": "Something went wrong. Please try again.",
    "twoFa.useBackupCode": "Use backup code instead",
    "twoFa.backupCode": "Backup code",
    
    // Payment Method
    "payment.title": "Payment Method",
    "payment.addNewCard": "Add New Card",
    "payment.noMethods": "No payment methods added yet",
    "payment.clickToAdd": "Click \"Add New Card\" to add a payment method",
    "payment.loading": "Loading payment methods...",
    "payment.cardholderName": "Cardholder Name",
    "payment.cardDetails": "Card Details",
    "payment.securePayment": "Secure Payment",
    "payment.encrypted": "Your payment information is encrypted and securely processed by Stripe. We never store your full card details.",
    "payment.saveMethod": "Save Payment Method",
    "payment.saving": "Saving...",
    "payment.addCard": "Add Card",
    "payment.expires": "Expires",
    "payment.deleteConfirm": "Are you sure you want to delete this payment method?",
    
    // Profile
    "profile.edit": "Edit Profile",
    "profile.view": "View Profile",
    "profile.yourJob": "Your Job",
    "profile.yourWork": "Your Work",
    "profile.contactClient": "Contact Client",
    "profile.contactProvider": "Contact Provider",
    "profile.viewClient": "View Client Profile",
    "profile.viewProvider": "View Provider Profile",
    "profile.allJobs": "All Jobs",
    "profile.activeJobs": "Active Jobs",
    "profile.completeJobs": "Complete Jobs",
    "profile.reviews": "Reviews",
    "profile.liked": "Liked",
    "profile.likedShowcaseColumn": "Showcase",
    "profile.likedJobsColumn": "Jobs",
    "profile.noLikedShowcases": "No liked showcases yet.",
    "profile.noLikedJobs": "No liked jobs yet.",
    "profile.loadingLiked": "Loading liked items…",
    "profile.saved": "Saved",
    "profile.noReviews": "No reviews yet",
    "profile.noSaved": "No saved profiles yet. Save profiles from the menu to see them here.",
    "profile.loadingSaved": "Loading saved profiles...",
    "profile.follow": "Follow",
    "profile.followBack": "Follow back",
    "profile.followClient": "Follow Client",
    "profile.followProvider": "Follow Provider",
    "profile.following": "Following",
    "profile.followingLabel": "Following",
    "profile.followersLabel": "Followers",
    "profile.unfollow": "Unfollow",
    "profile.unfollowConfirmSheet": "Unfollow {name}?",
    "profile.followerManageTitle": "Followers & Following",
    "profile.noFollowingYet": "Not following anyone yet",
    "profile.noFollowersYet": "No followers yet",
    "profile.removeFollower": "Remove follower",
    "profile.removeFollowerConfirm":
      "Remove this person from your followers? They will no longer follow you.",
    "profile.message": "Message",
    "profile.moreOptions": "More options",
    "profile.followSignIn": "Please sign in to follow profiles.",
    "profile.followError": "Could not update follow. Please try again.",
    "profile.showcases": "Showcases",
    "profile.jobs": "Jobs",
    "profile.saveProfile": "Save profile",
    "profile.removeSave": "Remove from Saved",
    "profile.qrCode": "QR Code",
    "profile.viewPhoto": "View profile photo",
    "profile.showLess": "Show less",
    "profile.viewAllSkills": "View all",
    "profile.provider": "Provider",
    "profile.filter": "Filter",
    "profile.jobsFilterAll": "All",
    "profile.jobsFilterActive": "Active",
    "profile.jobsFilterComplete": "Complete",

    // Reels (Flutter-style vertical feed)
    "reels.forYou": "For You",
    "reels.followingTab": "Following",
    "reels.back": "Back",
    "reels.mute": "Mute",
    "reels.unmute": "Unmute",
    "reels.volumeUp": "Increase volume",
    "reels.volumeDown": "Decrease volume",
    "reels.volumeControls": "Volume controls",
    "reels.volume": "Volume",
    "reels.volumeSlider": "Volume slider",
    "reels.upload": "Upload reel",
    "reels.noCaption": "No caption",
    "reels.emptyForYouTitle": "No reels yet",
    "reels.emptyForYouHint": "Tap + to upload your first reel.",
    "reels.emptyFollowingTitle": "No reels in Following",
    "reels.emptyFollowingHint": "Follow creators to see their latest reels here.",
    "reels.emptyFollowingHintFollowed": "People you follow have not posted reels yet.",
    "reels.uploadTitle": "Upload Reel",
    "reels.uploadSubtitle": "Short vertical video works best.",
    "reels.chooseVideo": "Choose a video file",
    "reels.caption": "Caption",
    "reels.uploading": "Uploading…",
    "reels.uploadButton": "Upload",
    "reels.uploadChooseError": "Choose a video file",
    "reels.uploadFailed": "Upload failed",
    "reels.searchPeopleTitle": "Search People",
    "reels.filterPeopleTitle": "Filter People",
    "reels.searchPlaceholder": "Search by username or name",
    "reels.searchAction": "Search",
    "reels.noPeopleFound": "No people found",
    "reels.follow": "Follow",
    "reels.followingLabel": "Following",
    "reels.roleAll": "All",
    "reels.roleProvider": "Provider",
    "reels.roleClient": "Client",
    "reels.searchPeople": "Search people",
    "reels.filterPeople": "Filter people",
    "reels.watchForYou": "Watch For You",
    "reels.refreshFollowing": "Refresh Following",
    "reels.loadFailed": "Something went wrong",
    "reels.retry": "Retry",
    "reels.goBack": "Go back",
    "reels.loadMoreFailed": "Failed to load more reels",
    "reels.comments": "Comments",
    "reels.noComments": "No comments yet",
    "reels.writeComment": "Write a comment…",
    
    // Job Details
    "job.title": "Job Details",
    "job.share": "Share Job",
    "job.contact": "Contact Client",
    "job.shareJob": "Share Job",
    "job.viewProfile": "View Profile",
    "job.description": "Description",
    "job.additionalInfo": "Additional Information",
    "job.created": "Created",
    "job.location": "Location",
    "job.budget": "Budget",
    "job.skills": "Skills",
    "job.estimatedDuration": "Estimated Duration",
    "job.hours": "hours",
    
    // Work Details
    "work.title": "Work Details",
    "work.share": "Share Work",
    "work.contact": "Contact Provider",
    "work.shareWork": "Share Work",
    "work.viewProfile": "View Profile",
    "work.description": "Description",
    "work.additionalInfo": "Additional Information",
    "work.created": "Created",
    "work.location": "Location",
    "work.skills": "Skills",
    "work.jobPositions": "JOB POSITIONS",
    
    // Common actions
    "actions.save": "Save",
    "actions.apply": "Apply",
    "actions.contact": "Contact",
    "actions.bookmark": "Bookmark",
    "actions.unbookmark": "Unbookmark",
    "actions.chat": "Chat",
    "actions.share": "Share",
    
    // Auth
    "auth.signIn": "Sign in",
    "auth.signInToAccount": "Sign in to your account",
    "auth.createAccount": "Create a new account",
    "auth.login": "Login",
    "auth.enterCredentials": "Enter your credentials to access your account",
    "auth.email": "Email address",
    "auth.password": "Password",
    "auth.forgotPassword": "Forget Password?",
    "auth.signingIn": "Signing in...",
    "auth.continueWithGoogle": "Continue with Google",
    "auth.continueWithApple": "Continue with Apple",
    "auth.signUpWithGoogle": "Sign up with Google",
    "auth.signUpWithApple": "Sign up with Apple",
    "auth.orContinueWith": "Or continue with",
    "auth.createYourAccount": "Create your account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.signUp": "Sign Up",
    "auth.joinTaskzing": "Join TaskZing and start connecting with professionals",
    "auth.fullName": "Full Name",
    "auth.confirmPassword": "Confirm Password",
    "auth.iWantTo": "I want to",
    "auth.hireProfessionals": "Hire professionals",
    "auth.offerServices": "Offer my services",
    "auth.mustBe6Chars": "Must be at least 6 characters",
    "auth.createAccountBtn": "Create Account",
    "auth.signingUp": "Signing up...",
    "auth.passwordsDoNotMatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters",
    "auth.invalidEmail": "Invalid email address.",
    "auth.userDisabled": "This account has been disabled.",
    "auth.userNotFound": "No account found with this email.",
    "auth.wrongPassword": "Incorrect password.",
    "auth.invalidCredential": "Invalid email or password.",
    "auth.tooManyRequests": "Too many failed attempts. Please try again later.",
    "auth.popupClosed": "Sign-in popup was closed. Please try again.",
    "auth.cancelled": "Sign-in was cancelled. Please try again.",
    "auth.popupBlocked": "Popup was blocked by browser. Please allow popups and try again.",
    "auth.unauthorizedDomain": "This domain is not authorized. Please contact support.",
    "auth.googleOriginMismatch":
      "Google sign-in blocked (origin mismatch). In Google Cloud Console, add this site's URL to Authorized JavaScript origins for the Web OAuth client, then try again.",
    "auth.operationNotAllowed":
      "Google or Apple sign-in is not enabled for this project. Enable the provider in Firebase Authentication.",
    "auth.accountExists": "An account already exists with a different sign-in method.",
    "auth.emailAlreadyInUse": "An account with this email already exists.",
    "auth.weakPassword": "Password is too weak. Please use a stronger password.",
    "auth.errorOccurred": "An error occurred. Please try again.",
    
    // Header
    "header.categories": "Categories",
    "header.howItWorks": "How It Works",
    "header.pricing": "Pricing",
    "header.about": "About",
    "header.searchTasks": "Search tasks...",
    "header.logIn": "Log In",
    "header.signUp": "Sign Up",
    "header.openApp": "Open app",
    
    // Home Page
    "home.madeInCanada": "Made in Canada 🇨🇦",
    "home.connectWithProfessionals": "Connect with Skilled Professionals",
    "home.bridgeGap": "TaskZing bridges the gap between those who need work done and those ready to offer it",
    "home.comprehensivePlatform": "A comprehensive task and job marketplace platform where clients post jobs and providers showcase their skills. Quality service, secure payments, real-time messaging.",
    "home.getStarted": "Get Started",
    "home.browseCategories": "Browse Categories",
    "home.forEveryone": "For Everyone",
    "home.worksForBoth": "TaskZing works for both clients and service providers. Switch roles seamlessly.",
    "home.forClients": "For Clients",
    "home.forClientsDesc": "Post jobs, find skilled professionals, manage projects, and get quality work done.",
    "home.postDetailedJobs": "Post detailed job listings with photos and location",
    "home.receiveProposals": "Receive proposals from qualified providers",
    "home.browsePortfolios": "Browse provider portfolios and reviews",
    "home.secureMessaging": "Secure messaging and communication",
    "home.protectedPayments": "Protected payments through Stripe",
    "home.rateReview": "Rate and review providers",
    "home.forProviders": "For Providers",
    "home.forProvidersDesc": "Showcase your skills, find jobs, build your reputation, and grow your business.",
    "home.createPortfolio": "Create a professional portfolio with photos and videos",
    "home.browseJobs": "Browse and apply to relevant job postings",
    "home.buildReputation": "Build your reputation through reviews and ratings",
    "home.securePayments": "Receive secure payments and build your reputation",
    "home.realTimeMessaging": "Real-time messaging with clients",
    "home.growBusiness": "Grow your business with TaskZing",
    "home.whyChoose": "Why Choose TaskZing?",
    "home.platformFeatures": "Platform features designed to make your experience smooth and secure",
    "home.locationBased": "Location-Based Services",
    "home.locationBasedDesc": "Find professionals near you with Google Maps integration and geolocation",
    "home.securePaymentsFeature": "Secure Payments",
    "home.securePaymentsDesc": "Protected transactions through Stripe with payment security",
    "home.realTimeMessagingFeature": "Real-Time Messaging",
    "home.realTimeMessagingDesc": "Instant communication with clients and providers",
    "home.dualRole": "Dual Role System",
    "home.dualRoleDesc": "Switch seamlessly between Client and Provider roles",
    "home.multiLanguage": "Multi-Language Support",
    "home.multiLanguageDesc": "Available in English and French",
    "home.aiPowered": "AI-Powered Assistant",
    "home.aiPoweredDesc": "Chat Zing - Your intelligent TaskZing assistant for help and support",
    "home.featuredCategories": "Featured Categories",
    "home.browseAll": "Browse All Categories",
    "home.featuredTasks": "Featured Tasks",
    "home.viewAll": "View All Tasks",
    "home.howItWorks": "How It Works",
    "home.howItWorksDesc": "Simple steps to get your tasks done or start offering your services",
    "home.postOrBrowse": "Post or Browse",
    "home.postOrBrowseDesc": "Clients post detailed job listings. Providers browse opportunities and showcase portfolios.",
    "home.connectPropose": "Connect & Propose",
    "home.connectProposeDesc": "Providers submit proposals. Clients review profiles, ratings, and portfolios.",
    "home.communicate": "Communicate",
    "home.communicateDesc": "Use real-time messaging to discuss details, track progress, and coordinate.",
    "home.completeReview": "Complete & Review",
    "home.completeReviewDesc": "Pay securely, complete the work, and leave reviews to build trust.",
    "home.learnMore": "Learn More About How It Works",
    "home.browseCategoriesTitle": "Browse Categories",
    "home.browseCategoriesDesc": "Find professionals by category",
    "home.viewAllCategories": "View All",
    "home.featuredJobs": "Featured Jobs",
    "home.featuredJobsDesc": "Latest opportunities for service providers",
    "home.viewAllJobs": "View All Jobs",
    "home.testimonials": "What Our Users Say",
    "home.testimonialsDesc": "Real experiences from clients and providers across Canada",
    "home.readyToStart": "Ready to Get Started?",
    "home.readyToStartDesc": "Join the TaskZing community - where clients find skilled professionals and providers discover opportunities across Canada",
    "home.createAccount": "Create Your Account",
    "home.learnHowItWorks": "Learn How It Works",
    
    // Filters
    "filter.title": "Filter your Choice",
    "filter.location": "Location",
    "filter.enterCity": "Enter city or address",
    "filter.area": "Area",
    "filter.enterArea": "Enter area or neighborhood",
    "filter.posterType": "Poster Type",
    "filter.rating": "Rating",
    "filter.dayPosted": "Day Posted",
    "filter.clearAll": "Clear All",
    "filter.applyFilter": "Apply Filter",
    "filter.all": "All",
    "filter.any": "Any",
    "filter.anyTime": "Any time",
    "filter.last24Hours": "Last 24 hours",
    "filter.last7Days": "Last 7 days",
    "filter.last30Days": "Last 30 days",
    "filter.individual": "Individual",
    "filter.company": "Company",
    "filter.inStore": "In Store",
    "filter.allStars": "All",
    "filter.5Stars": "5 Stars",
    "filter.4PlusStars": "4+ Stars",
    "filter.3PlusStars": "3+ Stars",
    "filter.2PlusStars": "2+ Stars",
    "filter.sortBy": "Sort By",
    "filter.newest": "Newest",
    "filter.oldest": "Oldest",
    "filter.ratingHighToLow": "Rating: High to Low",
    "filter.ratingLowToHigh": "Rating: Low to High",
    "filter.showSaved": "Show Saved",
    "filter.exploreHere": "Explore Here",
    "filter.noItemsFound": "No showcase items found. Try adjusting your filters.",
    
    // Explore Page (Provider)
    "explore.searchJobs": "Search jobs...",
    "explore.allCategories": "All Categories",
    "explore.projectTypes": "Project Types",
    "explore.all": "All",
    "explore.fixedPrice": "Fixed Price",
    "explore.hourlyRate": "Hourly Rate",
    "explore.posterTypes": "Poster Types",
    "explore.priceRanges": "Price Ranges",
    "explore.urgencyLevels": "Urgency Levels",
    "explore.urgent": "Urgent",
    "explore.high": "High",
    "explore.normal": "Normal",
    "explore.low": "Low",
    "explore.jobStatus": "Job Status",
    "explore.open": "Open",
    "explore.inProgress": "In Progress",
    "explore.noJobsFound": "No jobs found. Try adjusting your filters.",
  },
  french: {
    // Common
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.submit": "Soumettre",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.close": "Fermer",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.clear": "Effacer",
    "common.apply": "Appliquer",
    "common.or": "Ou",
    
    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.explore": "Explorer",
    "nav.reels": "Reels",
    "nav.showcasework": "Vitrine de travail",
    "nav.showcase": "Vitrine",
    "nav.mytasks": "Mes tâches",
    "nav.messages": "Messages",
    "nav.profile": "Profil",
    "nav.settings": "Paramètres",
    "nav.chatzing": "Chat Zing",
    "plus.chatzingAi": "ChatZing AI",
    "nav.home": "Accueil",
    "nav.postajob": "Publier un emploi",
    "nav.alljobs": "Tous les emplois",
    "nav.darkMode": "Mode sombre",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.description": "Gérez vos paramètres et préférences",
    "settings.darkLightMode": "Mode sombre/clair",
    "settings.currentlyLight": "Actuellement: Mode clair",
    "settings.currentlyDark": "Actuellement: Mode sombre (Thème bleu)",
    "settings.light": "Clair",
    "settings.dark": "Sombre",
    "settings.system": "Système",
    "settings.paymentMethod": "Méthode de paiement",
    "settings.addAccountDetails": "Ajoutez les détails de votre compte",
    "settings.addPayment": "Ajouter un paiement",
    "settings.notifications": "Notifications",
    "settings.toggleNotifications": "Basculer pour désactiver les notifications",
    "settings.suggestions": "Suggestions et plaintes",
    "settings.suggestionsDesc": "Partagez vos commentaires ou signalez des problèmes pour nous aider à nous améliorer",
    "settings.submitFeedback": "Soumettre des commentaires",
    "settings.terms": "Tous les termes et conditions",
    "settings.termsDesc": "Voir tous les termes par catégorie (Général, Prestataire, Utilisateur, Publier un emploi, Vitrine, Légal)",
    "settings.viewTerms": "Voir les termes",
    "settings.language": "Langue",
    "settings.chooseLanguage": "Choisissez votre langue préférée",
    "settings.english": "English",
    "settings.french": "Français",
    "settings.accountDeactivation": "Désactivation du compte",
    "settings.deactivateAccount": "Désactiver votre compte",
    "settings.deactivate": "Désactiver",
    "settings.logOut": "Déconnexion",
    "settings.signOut": "Déconnectez-vous de votre compte",
    "settings.loggingOut": "Déconnexion...",
    "settings.changePasswordTitle": "Changer le mot de passe",
    "settings.changePasswordDesc": "Mettre à jour le mot de passe de votre compte TaskZing",
    "settings.changePassword.back": "Retour",
    "settings.changePassword.current": "Mot de passe actuel",
    "settings.changePassword.new": "Nouveau mot de passe",
    "settings.changePassword.confirm": "Confirmer le nouveau mot de passe",
    "settings.changePassword.save": "Enregistrer",
    "settings.changePassword.saving": "Enregistrement…",
    "settings.changePassword.mismatch": "Les mots de passe ne correspondent pas",
    "settings.changePassword.success": "Mot de passe mis à jour. Les autres appareils ont été déconnectés.",
    "settings.changePassword.failed": "Impossible de mettre à jour le mot de passe. Réessayez.",
    "settings.changePassword.forgotLink": "Mot de passe oublié ? Envoyer un e-mail de réinitialisation",
    "settings.twoFactor": "Authentification à deux facteurs",
    "settings.twoFactorDesc": "Application d'authentification (TOTP)",
    "settings.reels": "Reels",
    "settings.reelsDesc": "Regardez et publiez de courtes vidéos",
    "settings.notificationsOn": "Notifications activées",
    "settings.notificationsOff": "Notifications désactivées",
    "settings.confirmLogoutTitle": "Déconnexion",
    "settings.confirmLogoutMessage": "Se déconnecter de votre compte ?",
    "settings.cancel": "Annuler",
    "settings.accountDeletion": "Suppression du compte",
    "settings.accountDeletionDesc": "Supprimer définitivement votre compte après 90 jours",
    "settings.deleteAccount": "Supprimer le compte",
    "settings.deleteAccountDesc": "Supprimer définitivement votre compte",
    "settings.deactivationConfirmTitle": "Confirmer la désactivation",
    "settings.deactivationConfirmMessage":
      "Votre compte sera désactivé. Contactez le support pour le réactiver. Continuer ?",
    "settings.deactivationSuccess": "Compte désactivé. Vous avez été déconnecté.",
    "settings.deactivationFailed": "Échec de la désactivation",
    "settings.deactivating": "Désactivation du compte…",
    "settings.deletionConfirmTitle": "Confirmer la suppression définitive",
    "settings.deletionConfirmMessage":
      "Votre compte sera désactivé maintenant et supprimé définitivement après 90 jours. Vous pouvez réactiver dans les 90 jours pour annuler. Après 90 jours, vos données seront supprimées automatiquement. Cette action est irréversible. Continuer ?",
    "settings.deletionConfirmButton": "Oui, supprimer mon compte",
    "settings.deletionSuccess":
      "Demande enregistrée. Votre compte sera supprimé définitivement sous 90 jours.",
    "settings.deletionFailed": "Échec de la demande",
    "settings.deletionInfo":
      "Votre compte sera désactivé et programmé pour suppression définitive après 90 jours. Vous pouvez réactiver dans les 90 jours pour annuler.",
    "settings.deletionReasonTitle": "Choisissez une raison pour supprimer définitivement votre compte",
    "settings.requestPermanentDeletion": "Demander la suppression définitive",
    "settings.deletionEmailHint": "Ou demander par e-mail :",
    "settings.deletionEmailBody":
      "Je souhaite demander la suppression définitive de mon compte TaskZing.",
    "settings.deletionEmailSubject": "Demande de suppression de compte",
    "settings.deletionEmailOpened":
      "Votre client e-mail va s'ouvrir. Envoyez le message pour compléter la demande.",
    "settings.deletionEmailFailed": "Impossible d'ouvrir le client e-mail. Écrivez-nous à",
    "settings.feedbackSuccess":
      "Merci pour vos commentaires ! Votre soumission a été reçue.",

    "twoFa.title": "Authentification à deux facteurs",
    "twoFa.back": "Retour",
    "twoFa.disabledDescription":
      "Protégez votre compte avec l'authentification à deux facteurs. Scannez un code QR, confirmez avec un code envoyé par e-mail, puis enregistrez les codes de secours.",
    "twoFa.enabledDescription":
      "L'authentification à deux facteurs est activée. À la connexion, un code envoyé par e-mail sera également requis.",
    "twoFa.startSetup": "Commencer la configuration",
    "twoFa.sendEnableCode": "Envoyer le code d'activation par e-mail",
    "twoFa.enterEmailCode": "Entrez le code reçu par e-mail",
    "twoFa.enableButton": "Activer la 2FA",
    "twoFa.secretLabel": "Secret",
    "twoFa.turnOffTitle": "Désactiver la 2FA",
    "twoFa.password": "Mot de passe",
    "twoFa.backupCodeOptional": "Code de secours (facultatif si vous utilisez le code e-mail)",
    "twoFa.sendDisableCode": "Envoyer le code de désactivation par e-mail",
    "twoFa.emailCode": "Code e-mail",
    "twoFa.disableButton": "Désactiver la 2FA",
    "twoFa.saveBackupCodes": "Enregistrer les codes de secours",
    "twoFa.enableCodeSent": "Code d'activation envoyé à votre e-mail",
    "twoFa.disableCodeSent": "Code de désactivation envoyé à votre e-mail",
    "twoFa.enabledSuccess": "Authentification à deux facteurs activée",
    "twoFa.disabledSuccess": "Authentification à deux facteurs désactivée",
    "twoFa.passwordRequired": "Le mot de passe est requis",
    "twoFa.codeSixDigits": "Entrez le code à 6 chiffres reçu par e-mail",
    "twoFa.errorGeneric": "Une erreur s'est produite. Veuillez réessayer.",
    "twoFa.useBackupCode": "Utiliser un code de secours",
    "twoFa.backupCode": "Code de secours",
    
    // Payment Method
    "payment.title": "Méthode de paiement",
    "payment.addNewCard": "Ajouter une nouvelle carte",
    "payment.noMethods": "Aucune méthode de paiement ajoutée",
    "payment.clickToAdd": "Cliquez sur \"Ajouter une nouvelle carte\" pour ajouter une méthode de paiement",
    "payment.loading": "Chargement des méthodes de paiement...",
    "payment.cardholderName": "Nom du titulaire",
    "payment.cardDetails": "Détails de la carte",
    "payment.securePayment": "Paiement sécurisé",
    "payment.encrypted": "Vos informations de paiement sont cryptées et traitées en toute sécurité par Stripe. Nous ne stockons jamais les détails complets de votre carte.",
    "payment.saveMethod": "Enregistrer la méthode de paiement",
    "payment.saving": "Enregistrement...",
    "payment.addCard": "Ajouter la carte",
    "payment.expires": "Expire",
    "payment.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette méthode de paiement?",
    
    // Profile
    "profile.edit": "Modifier le profil",
    "profile.view": "Voir le profil",
    "profile.yourJob": "Votre emploi",
    "profile.yourWork": "Votre travail",
    "profile.contactClient": "Contacter le client",
    "profile.contactProvider": "Contacter le prestataire",
    "profile.viewClient": "Voir le profil du client",
    "profile.viewProvider": "Voir le profil du prestataire",
    "profile.allJobs": "Tous les emplois",
    "profile.activeJobs": "Emplois actifs",
    "profile.completeJobs": "Emplois terminés",
    "profile.reviews": "Avis",
    "profile.liked": "Aimés",
    "profile.likedShowcaseColumn": "Vitrine",
    "profile.likedJobsColumn": "Emplois",
    "profile.noLikedShowcases": "Aucune vitrine aimée pour le moment.",
    "profile.noLikedJobs": "Aucun emploi aimé pour le moment.",
    "profile.loadingLiked": "Chargement des éléments aimés…",
    "profile.saved": "Enregistré",
    "profile.noReviews": "Pas encore d'avis",
    "profile.noSaved": "Aucun profil enregistré. Enregistrez des profils depuis le menu pour les voir ici.",
    "profile.loadingSaved": "Chargement des profils enregistrés...",
    "profile.follow": "Suivre",
    "profile.followBack": "Suivre en retour",
    "profile.followClient": "Suivre le client",
    "profile.followProvider": "Suivre le prestataire",
    "profile.following": "Suivi",
    "profile.followingLabel": "Abonnements",
    "profile.followersLabel": "Abonnés",
    "profile.unfollow": "Ne plus suivre",
    "profile.unfollowConfirmSheet": "Ne plus suivre {name} ?",
    "profile.followerManageTitle": "Abonnés et abonnements",
    "profile.noFollowingYet": "Vous ne suivez personne pour le moment",
    "profile.noFollowersYet": "Aucun abonné pour le moment",
    "profile.removeFollower": "Retirer l'abonné",
    "profile.removeFollowerConfirm":
      "Retirer cette personne de vos abonnés ? Elle ne vous suivra plus.",
    "profile.message": "Message",
    "profile.moreOptions": "Plus d'options",
    "profile.followSignIn": "Connectez-vous pour suivre des profils.",
    "profile.followError": "Impossible de mettre à jour le suivi. Réessayez.",
    "profile.showcases": "Vitrines",
    "profile.jobs": "Emplois",
    "profile.saveProfile": "Enregistrer le profil",
    "profile.removeSave": "Retirer des enregistrés",
    "profile.qrCode": "Code QR",
    "profile.viewPhoto": "Voir la photo de profil",
    "profile.showLess": "Réduire",
    "profile.viewAllSkills": "Voir tout",
    "profile.provider": "Prestataire",
    "profile.filter": "Filtrer",
    "profile.jobsFilterAll": "Tous",
    "profile.jobsFilterActive": "Actifs",
    "profile.jobsFilterComplete": "Terminés",

    // Reels
    "reels.forYou": "Pour vous",
    "reels.followingTab": "Abonnements",
    "reels.back": "Retour",
    "reels.mute": "Couper le son",
    "reels.unmute": "Activer le son",
    "reels.volumeUp": "Augmenter le volume",
    "reels.volumeDown": "Diminuer le volume",
    "reels.volumeControls": "Contrôles du volume",
    "reels.volume": "Volume",
    "reels.volumeSlider": "Curseur de volume",
    "reels.upload": "Publier une reel",
    "reels.noCaption": "Aucune légende",
    "reels.emptyForYouTitle": "Aucune reel pour le moment",
    "reels.emptyForYouHint": "Appuyez sur + pour publier votre première reel.",
    "reels.emptyFollowingTitle": "Aucune reel dans Abonnements",
    "reels.emptyFollowingHint": "Suivez des créateurs pour voir leurs reels ici.",
    "reels.emptyFollowingHintFollowed": "Les personnes que vous suivez n'ont pas encore publié de reels.",
    "reels.uploadTitle": "Publier une reel",
    "reels.uploadSubtitle": "Une vidéo verticale courte convient le mieux.",
    "reels.chooseVideo": "Choisir une vidéo",
    "reels.caption": "Légende",
    "reels.uploading": "Publication…",
    "reels.uploadButton": "Publier",
    "reels.uploadChooseError": "Choisissez une vidéo",
    "reels.uploadFailed": "Échec de la publication",
    "reels.searchPeopleTitle": "Rechercher",
    "reels.filterPeopleTitle": "Filtrer",
    "reels.searchPlaceholder": "Nom ou nom d'utilisateur",
    "reels.searchAction": "Rechercher",
    "reels.noPeopleFound": "Aucune personne trouvée",
    "reels.follow": "Suivre",
    "reels.followingLabel": "Abonné",
    "reels.roleAll": "Tous",
    "reels.roleProvider": "Prestataire",
    "reels.roleClient": "Client",
    "reels.searchPeople": "Rechercher",
    "reels.filterPeople": "Filtrer",
    "reels.watchForYou": "Voir Pour vous",
    "reels.refreshFollowing": "Actualiser",
    "reels.loadFailed": "Une erreur s'est produite",
    "reels.retry": "Réessayer",
    "reels.goBack": "Retour",
    "reels.loadMoreFailed": "Impossible de charger plus de reels",
    "reels.comments": "Commentaires",
    "reels.noComments": "Aucun commentaire",
    "reels.writeComment": "Écrire un commentaire…",
    
    // Job Details
    "job.title": "Détails de l'emploi",
    "job.share": "Partager l'emploi",
    "job.contact": "Contacter le client",
    "job.shareJob": "Partager l'emploi",
    "job.viewProfile": "Voir le profil",
    "job.description": "Description",
    "job.additionalInfo": "Informations supplémentaires",
    "job.created": "Créé",
    "job.location": "Emplacement",
    "job.budget": "Budget",
    "job.skills": "Compétences",
    "job.estimatedDuration": "Durée estimée",
    "job.hours": "heures",
    
    // Work Details
    "work.title": "Détails du travail",
    "work.share": "Partager le travail",
    "work.contact": "Contacter le prestataire",
    "work.shareWork": "Partager le travail",
    "work.viewProfile": "Voir le profil",
    "work.description": "Description",
    "work.additionalInfo": "Informations supplémentaires",
    "work.created": "Créé",
    "work.location": "Emplacement",
    "work.skills": "Compétences",
    "work.jobPositions": "POSTES D'EMPLOI",
    
    // Common actions
    "actions.save": "Enregistrer",
    "actions.apply": "Postuler",
    "actions.contact": "Contacter",
    "actions.bookmark": "Marquer",
    "actions.unbookmark": "Retirer le marque-page",
    "actions.chat": "Chat",
    "actions.share": "Partager",
    
    // Auth
    "auth.signIn": "Se connecter",
    "auth.signInToAccount": "Connectez-vous à votre compte",
    "auth.createAccount": "Créer un nouveau compte",
    "auth.login": "Connexion",
    "auth.enterCredentials": "Entrez vos identifiants pour accéder à votre compte",
    "auth.email": "Adresse e-mail",
    "auth.password": "Mot de passe",
    "auth.forgotPassword": "Mot de passe oublié?",
    "auth.signingIn": "Connexion...",
    "auth.continueWithGoogle": "Continuer avec Google",
    "auth.continueWithApple": "Continuer avec Apple",
    "auth.signUpWithGoogle": "S'inscrire avec Google",
    "auth.signUpWithApple": "S'inscrire avec Apple",
    "auth.orContinueWith": "Ou continuer avec",
    "auth.createYourAccount": "Créez votre compte",
    "auth.alreadyHaveAccount": "Vous avez déjà un compte?",
    "auth.signUp": "S'inscrire",
    "auth.joinTaskzing": "Rejoignez TaskZing et commencez à vous connecter avec des professionnels",
    "auth.fullName": "Nom complet",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.iWantTo": "Je veux",
    "auth.hireProfessionals": "Embaucher des professionnels",
    "auth.offerServices": "Offrir mes services",
    "auth.mustBe6Chars": "Doit contenir au moins 6 caractères",
    "auth.createAccountBtn": "Créer un compte",
    "auth.signingUp": "Inscription...",
    "auth.passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
    "auth.passwordTooShort": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.invalidEmail": "Adresse e-mail invalide.",
    "auth.userDisabled": "Ce compte a été désactivé.",
    "auth.userNotFound": "Aucun compte trouvé avec cet e-mail.",
    "auth.wrongPassword": "Mot de passe incorrect.",
    "auth.invalidCredential": "E-mail ou mot de passe invalide.",
    "auth.tooManyRequests": "Trop de tentatives échouées. Veuillez réessayer plus tard.",
    "auth.popupClosed": "La fenêtre de connexion a été fermée. Veuillez réessayer.",
    "auth.cancelled": "La connexion a été annulée. Veuillez réessayer.",
    "auth.popupBlocked": "La fenêtre contextuelle a été bloquée par le navigateur. Veuillez autoriser les fenêtres contextuelles et réessayer.",
    "auth.unauthorizedDomain": "Ce domaine n'est pas autorisé. Veuillez contacter le support.",
    "auth.googleOriginMismatch":
      "Connexion Google bloquée (origine non autorisée). Ajoutez l'URL de ce site aux origines JavaScript autorisées du client OAuth Web dans Google Cloud Console, puis réessayez.",
    "auth.operationNotAllowed":
      "La connexion Google ou Apple n'est pas activée pour ce projet. Activez le fournisseur dans Firebase Authentication.",
    "auth.accountExists": "Un compte existe déjà avec une méthode de connexion différente.",
    "auth.emailAlreadyInUse": "Un compte avec cet e-mail existe déjà.",
    "auth.weakPassword": "Le mot de passe est trop faible. Veuillez utiliser un mot de passe plus fort.",
    "auth.errorOccurred": "Une erreur s'est produite. Veuillez réessayer.",
    
    // Header
    "header.categories": "Catégories",
    "header.howItWorks": "Comment ça marche",
    "header.pricing": "Tarification",
    "header.about": "À propos",
    "header.searchTasks": "Rechercher des tâches...",
    "header.logIn": "Se connecter",
    "header.signUp": "S'inscrire",
    "header.openApp": "Ouvrir l'app",
    
    // Home Page
    "home.madeInCanada": "Fabriqué au Canada 🇨🇦",
    "home.connectWithProfessionals": "Connectez-vous avec des professionnels qualifiés",
    "home.bridgeGap": "TaskZing comble le fossé entre ceux qui ont besoin de travail et ceux qui sont prêts à l'offrir",
    "home.comprehensivePlatform": "Une plateforme complète de marché de tâches et d'emplois où les clients publient des emplois et les prestataires présentent leurs compétences. Service de qualité, paiements sécurisés, messagerie en temps réel.",
    "home.getStarted": "Commencer",
    "home.browseCategories": "Parcourir les catégories",
    "home.forEveryone": "Pour tous",
    "home.worksForBoth": "TaskZing fonctionne pour les clients et les prestataires de services. Changez de rôle en toute transparence.",
    "home.forClients": "Pour les clients",
    "home.forClientsDesc": "Publiez des emplois, trouvez des professionnels qualifiés, gérez des projets et obtenez un travail de qualité.",
    "home.postDetailedJobs": "Publiez des offres d'emploi détaillées avec photos et emplacement",
    "home.receiveProposals": "Recevez des propositions de prestataires qualifiés",
    "home.browsePortfolios": "Parcourez les portfolios et avis des prestataires",
    "home.secureMessaging": "Messagerie et communication sécurisées",
    "home.protectedPayments": "Paiements protégés via Stripe",
    "home.rateReview": "Évaluez et commentez les prestataires",
    "home.forProviders": "Pour les prestataires",
    "home.forProvidersDesc": "Présentez vos compétences, trouvez des emplois, construisez votre réputation et développez votre entreprise.",
    "home.createPortfolio": "Créez un portfolio professionnel avec photos et vidéos",
    "home.browseJobs": "Parcourez et postulez aux offres d'emploi pertinentes",
    "home.buildReputation": "Construisez votre réputation grâce aux avis et notes",
    "home.securePayments": "Recevez des paiements sécurisés et construisez votre réputation",
    "home.realTimeMessaging": "Messagerie en temps réel avec les clients",
    "home.growBusiness": "Développez votre entreprise avec TaskZing",
    "home.whyChoose": "Pourquoi choisir TaskZing?",
    "home.platformFeatures": "Fonctionnalités de la plateforme conçues pour rendre votre expérience fluide et sécurisée",
    "home.locationBased": "Services basés sur la localisation",
    "home.locationBasedDesc": "Trouvez des professionnels près de chez vous avec l'intégration Google Maps et la géolocalisation",
    "home.securePaymentsFeature": "Paiements sécurisés",
    "home.securePaymentsDesc": "Transactions protégées via Stripe avec sécurité des paiements",
    "home.realTimeMessagingFeature": "Messagerie en temps réel",
    "home.realTimeMessagingDesc": "Communication instantanée avec les clients et les prestataires",
    "home.dualRole": "Système de double rôle",
    "home.dualRoleDesc": "Basculez facilement entre les rôles Client et Prestataire",
    "home.multiLanguage": "Support multilingue",
    "home.multiLanguageDesc": "Disponible en anglais et en français",
    "home.aiPowered": "Assistant alimenté par l'IA",
    "home.aiPoweredDesc": "Chat Zing - Votre assistant intelligent TaskZing pour l'aide et le support",
    "home.featuredCategories": "Catégories en vedette",
    "home.browseAll": "Parcourir toutes les catégories",
    "home.featuredTasks": "Tâches en vedette",
    "home.viewAll": "Voir toutes les tâches",
    "home.howItWorks": "Comment ça marche",
    "home.howItWorksDesc": "Étapes simples pour faire vos tâches ou commencer à offrir vos services",
    "home.postOrBrowse": "Publier ou parcourir",
    "home.postOrBrowseDesc": "Les clients publient des offres d'emploi détaillées. Les prestataires parcourent les opportunités et présentent leurs portfolios.",
    "home.connectPropose": "Se connecter et proposer",
    "home.connectProposeDesc": "Les prestataires soumettent des propositions. Les clients examinent les profils, les notes et les portfolios.",
    "home.communicate": "Communiquer",
    "home.communicateDesc": "Utilisez la messagerie en temps réel pour discuter des détails, suivre les progrès et coordonner.",
    "home.completeReview": "Terminer et évaluer",
    "home.completeReviewDesc": "Payez en toute sécurité, terminez le travail et laissez des avis pour établir la confiance.",
    "home.learnMore": "En savoir plus sur le fonctionnement",
    "home.browseCategoriesTitle": "Parcourir les catégories",
    "home.browseCategoriesDesc": "Trouvez des professionnels par catégorie",
    "home.viewAllCategories": "Voir tout",
    "home.featuredJobs": "Emplois en vedette",
    "home.featuredJobsDesc": "Dernières opportunités pour les prestataires de services",
    "home.viewAllJobs": "Voir tous les emplois",
    "home.testimonials": "Ce que disent nos utilisateurs",
    "home.testimonialsDesc": "Expériences réelles de clients et de prestataires à travers le Canada",
    "home.readyToStart": "Prêt à commencer?",
    "home.readyToStartDesc": "Rejoignez la communauté TaskZing - où les clients trouvent des professionnels qualifiés et les prestataires découvrent des opportunités à travers le Canada",
    "home.createAccount": "Créer votre compte",
    "home.learnHowItWorks": "Apprendre comment ça marche",
    
    // Filters
    "filter.title": "Filtrez votre choix",
    "filter.location": "Emplacement",
    "filter.enterCity": "Entrez la ville ou l'adresse",
    "filter.area": "Zone",
    "filter.enterArea": "Entrez la zone ou le quartier",
    "filter.posterType": "Type d'auteur",
    "filter.rating": "Note",
    "filter.dayPosted": "Jour de publication",
    "filter.clearAll": "Tout effacer",
    "filter.applyFilter": "Appliquer le filtre",
    "filter.all": "Tous",
    "filter.any": "Tous",
    "filter.anyTime": "N'importe quand",
    "filter.last24Hours": "Dernières 24 heures",
    "filter.last7Days": "7 derniers jours",
    "filter.last30Days": "30 derniers jours",
    "filter.individual": "Individuel",
    "filter.company": "Entreprise",
    "filter.inStore": "En magasin",
    "filter.allStars": "Tous",
    "filter.5Stars": "5 étoiles",
    "filter.4PlusStars": "4+ étoiles",
    "filter.3PlusStars": "3+ étoiles",
    "filter.2PlusStars": "2+ étoiles",
    "filter.sortBy": "Trier par",
    "filter.newest": "Plus récent",
    "filter.oldest": "Plus ancien",
    "filter.ratingHighToLow": "Note: Du plus haut au plus bas",
    "filter.ratingLowToHigh": "Note: Du plus bas au plus haut",
    "filter.showSaved": "Afficher les enregistrés",
    "filter.exploreHere": "Explorer ici",
    "filter.noItemsFound": "Aucun élément de vitrine trouvé. Essayez d'ajuster vos filtres.",
    
    // Explore Page (Provider)
    "explore.searchJobs": "Rechercher des emplois...",
    "explore.allCategories": "Toutes les catégories",
    "explore.projectTypes": "Types de projet",
    "explore.all": "Tous",
    "explore.fixedPrice": "Prix fixe",
    "explore.hourlyRate": "Tarif horaire",
    "explore.posterTypes": "Types d'auteur",
    "explore.priceRanges": "Gammes de prix",
    "explore.urgencyLevels": "Niveaux d'urgence",
    "explore.urgent": "Urgent",
    "explore.high": "Élevé",
    "explore.normal": "Normal",
    "explore.low": "Faible",
    "explore.jobStatus": "Statut de l'emploi",
    "explore.open": "Ouvert",
    "explore.inProgress": "En cours",
    "explore.noJobsFound": "Aucun emploi trouvé. Essayez d'ajuster vos filtres.",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("english");

  useEffect(() => {
    // Load saved language preference
    const savedLanguage = localStorage.getItem("taskzing_language") as Language | null;
    if (savedLanguage === "english" || savedLanguage === "french") {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("taskzing_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
