/**
 * Ghost-text pools for Edit Profile (multi-word phrases + tokens so
 * suggestions continue after spaces, not only on the first word).
 */

export const PROFILE_FULL_NAME_SUGGESTIONS: readonly string[] = [
  "Alex Johnson",
  "Jordan Lee",
  "Sam Patel",
  "Taylor Morgan",
  "Riley Chen",
  "Casey Williams",
  "Jamie Singh",
  "Morgan Brooks",
  "Avery Nguyen",
  "Quinn Martinez",
  "Reese Thompson",
  "Skyler Kumar",
  "Drew Anderson",
  "Cameron Shah",
  "Blake Robinson",
];

export const PROFILE_USERNAME_SUGGESTIONS: readonly string[] = [
  "alex_designs",
  "jordanbuilds",
  "sam_services",
  "taylor_tasks",
  "rileycreates",
  "casey_pro",
  "jamie_helps",
  "morgan_fixes",
  "averyworks",
  "quinncrafts",
  "reesebuilds",
  "skyler_handy",
  "drewtech",
  "cameroncare",
  "blakebuild",
];

export const PROFILE_LOCATION_SUGGESTIONS: readonly string[] = [
  "Toronto ON Canada",
  "Vancouver BC Canada",
  "Montreal QC Canada",
  "Calgary AB Canada",
  "Edmonton AB Canada",
  "Ottawa ON Canada",
  "Winnipeg MB Canada",
  "Halifax NS Canada",
  "Victoria BC Canada",
  "Kitchener ON Canada",
  "Mississauga ON Canada",
  "North York Toronto",
  "Downtown Vancouver",
  "Old Montreal",
  "Kensington Calgary",
];

export const PROFILE_BIO_SUGGESTIONS: readonly string[] = [
  "i am a",
  "i have over",
  "years of experience",
  "in residential and",
  "commercial projects",
  "i specialize in",
  "fast turnaround",
  "clear communication",
  "fully insured",
  "licensed professional",
  "happy to help",
  "with small repairs",
  "and larger renovations",
  "based in",
  "available evenings",
  "and weekends",
  "references available",
  "on request",
  "i bring tools",
  "and supplies",
  "unless you prefer",
  "your own materials",
];

export const PROFILE_SKILL_SUGGESTIONS: readonly string[] = [
  "plumbing",
  "electrical",
  "carpentry",
  "painting",
  "cleaning",
  "landscaping",
  "moving",
  "assembly",
  "hvac",
  "drywall",
  "tiling",
  "roofing",
  "photography",
  "web design",
  "data entry",
  "bookkeeping",
  "tutoring",
  "dog walking",
  "pet sitting",
  "delivery",
];
